services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      POSTGRES_DB: "service"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "8080:8080"

  db:
    image: postgres:16.0
    container_name: db
    environment:
      POSTGRES_DB: "service"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
